# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.cache/wt [current_project]
set_property parent.project_path /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/image.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_1.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_9.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_0.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_8.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_7.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_6.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_5.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/filter2.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/filter1.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_4.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_bias.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/filter3.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_3.mem
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/dens_2.mem
}
read_verilog -library xil_defaultlib {
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/ReLu.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/clock_divider.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/clock_divider_dens.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/clock_divider_max.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/controlMemoryAddressConv.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/controlMemoryAddressImg.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/convolution.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/counterPositionMemMax.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/counterPositionRstlConv.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/counterPositionRstlMax.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/full_connected.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/maxpooling.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_0.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_1.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_2.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_3.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_4.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_5.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_6.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_7.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_8.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_dens_9.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_filter_1.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_filter_2.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_filter_3.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_image.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_rstl_conv_1.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_rstl_conv_2.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_rstl_conv_3.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/memory_rstl_max_1.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/quantization.v
  /home/javier/Documents/fpga_implementations_of_neural_networks/CNN/02_hardware/06_CNN_IP_core_z20/06_CNN_IP_core_z20.srcs/sources_1/imports/new/accQuant.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top accQuant -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef accQuant.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file accQuant_utilization_synth.rpt -pb accQuant_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
